// Code generated by protoc-gen-nidhi. DO NOT EDIT.
// source: test_data/test.proto

package fuzz

import (
	fuzz "github.com/google/gofuzz"
	pb "github.com/srikrsna/zapproto/test_data"
)

func FuzzPerson(msg *pb.Person, c fuzz.Continue) {
    c.Fuzz(&msg.Name)
    c.Fuzz(&msg.Age)
    c.Fuzz(&msg.Dob)
    c.Fuzz(&msg.MaritalStatus)
    c.Fuzz(&msg.Siblings)
    c.Fuzz(&msg.HoursPerWeek)
    c.Fuzz(&msg.Alive)
    c.Fuzz(&msg.FavouriteBooks)
    c.Fuzz(&msg.FavDays)
    c.Fuzz(&msg.Metadata)
    switch c.Int31n(3) {
    case 0:
        var f pb.Person_Male
        c.Fuzz(&f)
        msg.Gender = &f
    case 1:
        var f pb.Person_Female
        c.Fuzz(&f)
        msg.Gender = &f
    case 2:
        var f pb.Person_Other
        c.Fuzz(&f)
        msg.Gender = &f
    }
}
 
func FuzzPerson_Male(msg *pb.Person_Male, c fuzz.Continue) {
    c.Fuzz(&msg.Male)
}
 
func FuzzPerson_Female(msg *pb.Person_Female, c fuzz.Continue) {
    c.Fuzz(&msg.Female)
}
 
func FuzzPerson_Other(msg *pb.Person_Other, c fuzz.Continue) {
    c.Fuzz(&msg.Other)
}

func FuzzBooks(msg *pb.Books, c fuzz.Continue) {
    c.Fuzz(&msg.Books)
}
